### ISSUE TITLE
Narrow Message Types being passed into SubmitCallback or GetCallback 

### ISSUE THREAD

**Issue by chris-tbd** [TBD54566975/tbdex-kt#151]
Discord Thread: https://discord.com/channels/937858703112155166/949067728709369856/1204494465541210162
JS PR: https://github.com/TBD54566975/tbdex-js/pull/156/files#diff-fe3b59c637fcb3e6e3b01742b42b35cb58e2160f60310da6d9fc1085ba5a4be3R21

Right now it isn't smooth to convert from a `Message` to one of its subtypes like `Rfq` from a dev standpoint. If for example you're writing your `SubmitCallback` and pass through your message, in the callback you'll need to write something similar to this:

```kotlin
val message: Rfq?

  try {
    message = Message.parse(call.receiveText()) as Rfq
  } catch (e: Exception) {
    val errorDetail = ErrorDetail(detail = "Parsing of TBDex message failed: ${e.message}")
    val errorResponse = ErrorResponse(listOf(errorDetail))
    call.respond(HttpStatusCode.BadRequest, errorResponse)
    return
  }
```

Ideally I think it'd be a better dev experience to have a convenience method that removes the optionality and looks something like:

```kotlin
val rfq = Rfq.from(message = message)
```

If that method could handle the optionality internally to avoid exposing any of that to devs I think it'd make for a better user experience.

**Comment by jiyoontbd** [comment]
hey @chris-tbd 

so sorry i completely blanked on this. it's on my todo list to include in our tbdex 1.0 release, so it _should_ get done this week.
