### ISSUE TITLE
getExchange() should take TypeId for exchangeId

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/tbdex-kt#171]
For `Message` objects, the `exchangeId` that is passed in and also returned back is of type `TypeId`. However, the `TbdexHttpClient.getExchange()` method requires a String for `exchangeId`, forcing the user to call `toString()` on the `exchangeId` they retrieve for previous messages.

```kt
val exchange = TbdexHttpClient.getExchange(
    requesterDid = customerDid,
    pfiDid = rfq.metadata.to,
    exchangeId = rfq.metadata.exchangeId.toString()
)
```

<img width="487" alt="image" src="https://github.com/TBD54566975/tbdex-kt/assets/15972783/195a6348-6152-478e-a778-56a463cad0e8">

**Comment by jiyoontbd** [comment]
closing - addressed in https://github.com/TBD54566975/tbdex-kt/pull/175
