### ISSUE TITLE
OfferingId Type Issues

### ISSUE THREAD

**Issue by chris-tbd** [TBD54566975/tbdex-kt#182]
Right now if I have an `Offering` object, the `id` property of that object is type `TypeId`. This means that every time I'd like to access it and pass it around, I end up having to call `toString()` on it. Could we either:

1. Change it to type `String`
2. Create a separate getter method that returns type `String` if `TypeId` is required for internal reasons

Example of usage in this PR: https://github.com/TBD54566975/developer.tbd.website/pull/1272

**Comment by phoebe-lew** [comment]
@mistermoe @jiyoontbd I remember us going back and forth on this - guess we can make the external data model a string and just use type ID to generate/do validation?

**Comment by mistermoe** [comment]
Yaaaaz! Big big nice
