### ISSUE TITLE
java.io.IOException: Cleartext HTTP traffic to json-schema.org not permitted

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/tbdex-kt#238]
![image](https://github.com/TBD54566975/tbdex-kt/assets/14976/574de981-80f3-4788-8d00-82f6b9f5a73b)

This is a weird one, with tbdex-kt I am now seeing an error when I have an offering which has payin/out like this:

```
    payin: {
      currencyCode: 'USD',
      methods: [
        {
          kind: 'CREDIT_CARD',
          requiredPaymentDetails: {
            $schema: 'http://json-schema.org/draft-07/schema#',
            title: 'Credit Card',
            type: 'object',
            required: ['cc_number', 'expiry_month', 'expiry_year', 'cvc', 'name'],
            additionalProperties: false,
            properties: {
              cc_number: {
                title: 'credit card number',
                type: 'string',
              },
  
```

if I change it to https I see same error which implies something is hard coding to json-schema via http?

**Comment by jiyoontbd** [comment]
@michaelneale so this works when you set `$schema` value to `http://json-schema.org/draft-07/schema#`, but does not work when you set it to `https://...`?

**Comment by jiyoontbd** [comment]
possibly an android-only issue? 🤔 we could repro if we stood up a kotlin pfi

**Comment by decentralgabe** [comment]
it needs to be http I believe, for draft 7...later drafts use https

**Comment by michaelneale** [comment]
@jiyoontbd yeah android only for that error, at least for draft 7 - didn't try others.

**Comment by michaelneale** [comment]
closing as this is draft 7 - and can work around.
