### ISSUE TITLE
Implement message/resource signing

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex-kt#6]

**Comment by andresuribe87** [comment]
Messages seem to be a high level concept that's not specific to tbdex. Is this interpretation correct? If so, then I would suggest having all signing/verification logic live outside of tbdex.

**Comment by phoebe-lew** [comment]
@andresuribe87 sorry, might not have been obvious but message is specifically referring to this spec: https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#messages
