### ISSUE TITLE
Explore and Add Feature usage examples in API Reference docs

### ISSUE THREAD

**Issue by leordev** [TBD54566975/tbdex-kt#99]
We need to explore a way to publish feature usage examples.

In kotlin we have a way to do this, example: https://tbd54566975.github.io/tbdex-kt/protocol/tbdex.sdk.protocol.serialization/-json/index.html

I suspect that we could do that in tsdocs and rust too... Just as a long comment in markdown...

**Comment by mistermoe** [comment]
@leordev can we close this out?

**Comment by leordev** [comment]
Yes we can, we validated that the examples can be added in regular kt docs and extracted by dokka!
